package com.mx.movilpyme.model;
// Generated Jul 4, 2018 8:03:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado")
public class Empleado implements java.io.Serializable {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(name = "numero_empleado")
    private String numeroEmpleado;
    private Character sexo;
    private Integer edad;
    private String nombre;
    @Column(name = "fecha_ingreso")
    private Date fechaIngreso;
    private Double sueldo;
    @Column(name = "lugar_trabajo")
    private String lugarTrabajo;
    private String telefono;
    @Column(name = "jefe_inmediato_id")
    private Integer jefeInmediatoId;
    private Character activo;
    @Column(name = "puesto_id")
    private Integer puestoId;
    private Boolean jefe;
    @Column(name = "horario_trabajo_id")
    private Integer horarioTrabajoId;
    @Column(name = "salario_quincenal")
    private Double salarioQuincenal;
    private String password;

    public Empleado() {
    }

    public Empleado(String numeroEmpleado) {
        this.numeroEmpleado = numeroEmpleado;
    }

    public Empleado(String numeroEmpleado, Character sexo, Integer edad, String nombre, Date fechaIngreso, Double sueldo, String lugarTrabajo, String telefono, Integer jefeInmediatoId, Character activo, Integer puestoId, Boolean jefe, Integer horarioTrabajoId, Double salarioQuincenal) {
        this.numeroEmpleado = numeroEmpleado;
        this.sexo = sexo;
        this.edad = edad;
        this.nombre = nombre;
        this.fechaIngreso = fechaIngreso;
        this.sueldo = sueldo;
        this.lugarTrabajo = lugarTrabajo;
        this.telefono = telefono;
        this.jefeInmediatoId = jefeInmediatoId;
        this.activo = activo;
        this.puestoId = puestoId;
        this.jefe = jefe;
        this.horarioTrabajoId = horarioTrabajoId;
        this.salarioQuincenal = salarioQuincenal;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNumeroEmpleado() {
        return this.numeroEmpleado;
    }

    public void setNumeroEmpleado(String numeroEmpleado) {
        this.numeroEmpleado = numeroEmpleado;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public Integer getEdad() {
        return this.edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public Double getSueldo() {
        return this.sueldo;
    }

    public void setSueldo(Double sueldo) {
        this.sueldo = sueldo;
    }

    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }

    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public Integer getJefeInmediatoId() {
        return this.jefeInmediatoId;
    }

    public void setJefeInmediatoId(Integer jefeInmediatoId) {
        this.jefeInmediatoId = jefeInmediatoId;
    }

    public Character getActivo() {
        return this.activo;
    }

    public void setActivo(Character activo) {
        this.activo = activo;
    }

    public Integer getPuestoId() {
        return this.puestoId;
    }

    public void setPuestoId(Integer puestoId) {
        this.puestoId = puestoId;
    }

    public Boolean getJefe() {
        return this.jefe;
    }

    public void setJefe(Boolean jefe) {
        this.jefe = jefe;
    }

    public Integer getHorarioTrabajoId() {
        return this.horarioTrabajoId;
    }

    public void setHorarioTrabajoId(Integer horarioTrabajoId) {
        this.horarioTrabajoId = horarioTrabajoId;
    }

    public Double getSalarioQuincenal() {
        return this.salarioQuincenal;
    }

    public void setSalarioQuincenal(Double salarioQuincenal) {
        this.salarioQuincenal = salarioQuincenal;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }

}
