package com.mx.movilpyme.model;
// Generated Jul 4, 2018 8:03:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario")
public class Horario implements java.io.Serializable {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String nombre;
    @Column(name = "hora_entrada")
    private Date horaEntrada;
    @Column(name = "hora_salida")
    private Date horaSalida;
    private Date tolerancia;
    private Integer retardos;

    public Horario() {
    }

    public Horario(String nombre, Date horaEntrada, Date horaSalida) {
        this.nombre = nombre;
        this.horaEntrada = horaEntrada;
        this.horaSalida = horaSalida;
    }

    public Horario(String nombre, Date horaEntrada, Date horaSalida, Date tolerancia, Integer retardos) {
        this.nombre = nombre;
        this.horaEntrada = horaEntrada;
        this.horaSalida = horaSalida;
        this.tolerancia = tolerancia;
        this.retardos = retardos;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getHoraEntrada() {
        return this.horaEntrada;
    }

    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }

    public Date getHoraSalida() {
        return this.horaSalida;
    }

    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    public Date getTolerancia() {
        return this.tolerancia;
    }

    public void setTolerancia(Date tolerancia) {
        this.tolerancia = tolerancia;
    }

    public Integer getRetardos() {
        return this.retardos;
    }

    public void setRetardos(Integer retardos) {
        this.retardos = retardos;
    }

}
