package com.mx.movilpyme.model;
// Generated Jul 4, 2018 8:03:36 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "registro")
public class Registro implements java.io.Serializable {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(name = "empleado_id")
    private int empleadoId;
    @Column(name = "concepto_id")
    private Integer conceptoId;
    @Column(name = "hora_entrada")
    private Date horaEntrada;
    @Column(name = "hora_salida")
    private Date horaSalida;
    @Column(name = "fecha_registro")
    private Date fechaRegistro;
    private Boolean retardo;

    public Registro() {
    }

    public Registro(int empleadoId, Date horaEntrada, Date fechaRegistro) {
        this.empleadoId = empleadoId;
        this.horaEntrada = horaEntrada;
        this.fechaRegistro = fechaRegistro;
    }

    public Registro(int empleadoId, Integer conceptoId, Date horaEntrada, Date horaSalida, Date fechaRegistro) {
        this.empleadoId = empleadoId;
        this.conceptoId = conceptoId;
        this.horaEntrada = horaEntrada;
        this.horaSalida = horaSalida;
        this.fechaRegistro = fechaRegistro;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getEmpleadoId() {
        return this.empleadoId;
    }

    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }

    public Integer getConceptoId() {
        return this.conceptoId;
    }

    public void setConceptoId(Integer conceptoId) {
        this.conceptoId = conceptoId;
    }

    public Date getHoraEntrada() {
        return this.horaEntrada;
    }

    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }

    public Date getHoraSalida() {
        return this.horaSalida;
    }

    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Boolean getRetardo() {
        return retardo;
    }

    public void setRetardo(Boolean retardo) {
        this.retardo = retardo;
    }

    @Override
    public String toString() {
        return "Registro{" + "id=" + id + ", empleadoId=" + empleadoId + ", conceptoId=" + conceptoId + ", horaEntrada=" + horaEntrada + ", horaSalida=" + horaSalida + ", fechaRegistro=" + fechaRegistro + ", retardo=" + retardo + '}';
    }
}
